import java.util.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {

        List<Item> iList = itemRepository.findAll();
        List<SalesPromotion> spList = salesPromotionRepository.findAll();

        List<String> sum2List = new ArrayList<String>();
        int sum3 = 0;
        int sum4 =0;

        String str = "============= 订餐明细 =============\n";
        double sum1 = 0,sum2 = 0;
        for(int i =0;i<inputs.size();i++){
            for(int j=0;j<iList.size();j++){
                if(inputs.get(i).split(" x ")[0].equals(iList.get(j).getId())) {
                    sum1 += Integer.parseInt(inputs.get(i).split(" x ")[1]) * iList.get(j).getPrice();

                    if(spList.get(1).getRelatedItems().indexOf(inputs.get(i).split(" x ")[0]) != -1){
                        sum2 += Integer.parseInt(inputs.get(i).split(" x ")[1])*iList.get(j).getPrice()/2;
                        sum2List.add(iList.get(j).getName());
                        sum3 += Integer.parseInt(inputs.get(i).split(" x ")[1])*iList.get(j).getPrice()/2;
                    } else{
                        sum2 += Integer.parseInt(inputs.get(i).split(" x ")[1])*iList.get(j).getPrice();
                    }
                }
            }
        }
        if(sum1>=30){
            int num = (int) (sum1/30);
            sum4 = 6*num;
            sum1 -= sum4;
        }

        if(sum1<sum2){
            for(int i =0;i<inputs.size();i++){
                for(int j=0;j<iList.size();j++){
                    if(inputs.get(i).split(" x ")[0].equals(iList.get(j).getId())) {
                        str +=  iList.get(j).getName()+" x "+ inputs.get(i).split(" x ")[1] +" = "+(int)(iList.get(j).getPrice() * Integer.parseInt(inputs.get(i).split(" x ")[1]))+"元\n";
                        //System.out.println(str);
                    }
                }
            }
            str += "-----------------------------------\n";
            str += "使用优惠:\n";
            str += spList.get(0).getDisplayName()+"，省"+sum4+"元\n";
            str += "-----------------------------------\n";
            str += "总计：" + (int)sum1 + "元\n";
            str += "===================================";
        }else if (sum2 < sum1){
            for(int i =0;i<inputs.size();i++){
                for(int j=0;j<iList.size();j++){
                    if(inputs.get(i).split(" x ")[0].equals(iList.get(j).getId())) {
                        str +=  iList.get(j).getName()+" x "+ inputs.get(i).split(" x ")[1] +" = "+(int)(iList.get(j).getPrice() * Integer.parseInt(inputs.get(i).split(" x ")[1]))+"元\n";
                        //System.out.println(str);
                    }
                }
            }
            str += "-----------------------------------\n";
            str += "使用优惠:\n";
            str += spList.get(1).getDisplayName()+"(";
            for(int i= 0;i<sum2List.size();i++){
                if(i == 0){
                    str += sum2List.get(i);
                }else{
                    str += "，"+sum2List.get(i);
                }
            }
            str += ")，省"+ sum3+"元\n";
            str += "-----------------------------------\n";
            str += "总计：" + (int)sum2 + "元\n";
            str += "===================================";
        }else{
            for(int i =0;i<inputs.size();i++){
                for(int j=0;j<iList.size();j++){
                    if(inputs.get(i).split(" x ")[0].equals(iList.get(j).getId())) {
                        str +=  iList.get(j).getName()+" x "+ inputs.get(i).split(" x ")[1] +" = "+(int)(iList.get(j).getPrice() * Integer.parseInt(inputs.get(i).split(" x ")[1]))+"元\n";
                        //System.out.println(str);
                    }
                }
            }
            str += "-----------------------------------\n";
            str += "总计：" + (int)sum1 + "元\n";
            str += "===================================";
        }
        //System.out.println(str);
       // System.out.println(sum1 + "+" + sum2);
        return str;
    }
}
